# The order in which the blueprints are listed dtermines their position in the navifation menu
MANGO_NAVBAR_MODULES:
  - browse_bp
  - basic_search_bp
  - metadata_schema_editor_bp
  # From the below blueprints, only one should be enabled in config.py
  - operator_group_manager_admin_bp
  - basic_user_group_manager_admin_bp

MANGO_NAVBAR_ADMIN_MODULES:
  - admin_admin_bp
  - template_overrides_admin_bp
  - mango_open_search_admin_bp
  - mango_open_search_stats_bp
  - operator_admin_bp
