MANGO_MODULE_BLUEPRINTS:
  - browse_bp
  - basic_search_bp
  - metadata_schema_editor_bp
  - operator_group_manager_admin_bp

MANGO_MODULE_ADMIN_BLUEPRINTS:
  - admin_admin_bp
  - template_overrides_admin_bp
  - mango_open_search_admin_bp
  - mango_open_search_stats_bp
  - operator_admin_bp
