---
zone: tier1_data_pilot

# my_gallery_view_override_for_collections:
#   source: common/collection_view.html.j2
#   target: myplugin/gallery.html.j2
#   matches:
#     any:
#       metadata:
#         match_type: any
#         items:
#           - mg.collection_type:
#             - gallery
#             - images
#           - mg.otheravu: hello
#       name:
#         - gallery
#       subtree:
#         - /a/e/f
#         - /gg/d/f
#     all:
#       path: /a/b/c
#       metadata:
#         match_type: any
#         items:
#           - mg.collection_type:
#             - gallery
#           - mg.anything: something

# match_all_collections:
#   source: common/collection_view.html.j2
#   target: overrides/collection_browse.html.j2
#   matches:
#     always: true

---
zone: icts_demo

# collection_view_iot:
#   source: collection_view
#   target: collection_iot.html.j2
#   matches:
#     always: true
---
zone: all
gallery_carrousel:
  source: common/collection_view.html.j2
  target: common/gallery_carrousel.html.j2
  matches:
    all:
      metadata:
        match_type: any
        items:
          - mg.collection_type: gallery_carrousel
collection_view_trash:
  source: common/collection_view.html.j2
  target: common/collection_view_trash.html.j2
  matches:
    all:
      subtree: '/{{zone}}/trash' #quotes needed as in principle {} are special characters
object_view_trash:
  source: common/object_view.html.j2
  target: common/object_view_trash.html.j2
  matches:
    all:
      subtree: '/{{zone}}/trash'

realm_powered_side_bar:
  source: sidebar.html.j2
  target: user_tantra/sidebar.html.j2
  matches: always

user_profile:
  source: user/myprofile.html.j2
  target: mango_overrides/user/myprofile.html.j2
  matches: always

base_template_header:
  source: header.html.j2
  target: mango_overrides/header.html.j2
  matches: always

group_members:
  source: user/group_members.html.j2
  target: mango_overrides/user/group_members.html.j2
  matches: always